---
# vars file for osp.servers
__osp_servers:
- name: frontend
  cloud: openstack
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m1.medium
  security_group: frontend
  meta:
    group: frontends
    deployment_name: QA

- name: app1
  cloud: openstack
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m1.medium
  security_group: apps
  meta:
    group: apps
    deployment_name: QA

- name: app2
  cloud: openstack
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m1.medium
  security_group: apps
  meta:
    group: apps
    deployment_name: QA

- name: db
  cloud: openstack
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m1.medium
  security_group: db
  meta:
    group: appdbs
    deployment_name: QA
