---
# tasks file for create, start and add floating IP on osp.servers
- name: Create server {{ _server.name }}
  os_server:
    name: "{{ _server.name }}"
    cloud: "{{ _server.cloud }}"
    image: "{{ _server.image }}"
    key_name: "{{ _server.key_name }}"
    flavor: "{{ _server.flavor | default('m1.medium') }}"
    security_groups: "{{ _server.security_group | default(_server.group) }}"
    auto_ip: false
    wait: true
    nics:
    - net-name: "{{ _server.network | default('int_network') }}"
    meta:
      group: "{{ _server.meta.group }}"
      deployment_name: "{{ _server.meta.deployment_name }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  register: r_os_server

- name: Start server {{ _server.name }}
  os_server_action:
    server: "{{ _server.name }}"
    cloud: openstack
    action: start
  when: r_os_server.server.vm_state == 'stopped'

- name: Add floating IP to {{ _server.name }}
  os_floating_ip:
    cloud: "{{ _server.cloud }}"
    reuse: true
    server: "{{ _server.name }}"
    network: "{{ _server.floating_ip_network | default('ext_network') }}"
    wait: true
    timeout: 200
